language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: qynUSWsAuhwncx9cK115pTDGUFtLrZ3VIrbOvY0pVWV8bf204WwJ8TdS7fy82ZVn0gzySOLebMc14AUwEawRCUdyoFbkl2oL3snF5CWkuT7Gh7p+40yAqM9sMuP4Yyrgc+VsEqAiCiGadXYKsQGrfgM4WA5n3BePJ3SXr/bRUEJCWiIO123p9m0rS+V1vcIX4XzYX5huPgP+btfbq3leqaFKrHjloCxUrQIPGIfaT7ksQc/iXuC7XWDk/2eqocx1wqrFVsxgMljHYl2ZlpIBNBUBaZG/JvGx0inH2PktUBMvfbCmk+tu5QgtT8kzfxLr2ksy5WkbRITfN/xmhrlZwYZQZH6BXcup4I9B0ESczQ6K9TYgXMEof4Y2Eurj5w9QdJPgm4t44RA0tWF/9xei7B8l9ciM0zrC0l4n1fYg2bZaA2/g4qRpiBwU6SEk7/K6BTZndaW6Se1ZVAwFo6xepw3y5S2C0QX3Wq3QANAo768QVSY1JXTQaWq1KMyBIYRZ43+f/noBPF3ZzrfrlK7nWXSdxdLXlcn1rIZ48nKktq7HjIXka62Q6+U2iNpykRpGKafF2ST3oLP8dWkncpTHsz84phHnQsQ9kwJgc+OLro1B/7WqJT9YYqyYT65SPOkPmmZkGgQT9dVpcmI+76MrpDlPvQrtxVgEo1ap4wgaku8=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
