language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: dzHYQCEsb2QKbHdtw9VVwP9uSSyMg5b4dXkGI7LjIlOG+AusR17MDhGvja7B4wyOoAfa2BuRFPHxmhIAdL9OYIheSD5xVTZk9EOtUiaCHRMNDAVtBVy2BfgDPd63H5f794uG9kZcLa7MQRNgermDOHYSTrQ0e//gEVxMZs/oa5PZ2Mgu6mJFwuKsvC668tsvfICWZ+WY52DXsLn9j2ONjmra3It4j308utCH53UbNooOSTPQBgNdjPplB119DSOODpmue3U7dIP7hLLSBhI8y13ATj21J/2eEonTajVgHgk7NVIobHCBicRyMusPC7hOGpDsBOhvmANaevJ8zIO4rDYW6X6la5ZSSjsjqFj+oXzysesi3KZGqo8fJnT9yijUivkAsepofuq+Qj3PaNczTll5+aKOtsG6ssy9oaXr94Ru86a+/t2l253xSKztds4z3RjxPTc2IQ4iW3mV/oxBt96gETwbYzgImeNG/y+U5uZbyD1oN7BU3cWN1q4Jm8Y24GrlRlYaueOHbG1x/csMp4xCEJE6LUGn6adEvpEh2Lrz040IWTa9SNI2X2Vc6hwqBwSTO6cVsSgQ7luvqeUQLXPgmk1e5kneGH+lyARsBBQVevj9SDe3vi3ed8vQsYChImPcoZq6by6OffQJLUL7zZFRetSushsk99RuEX2HISs=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
